packages/WebApp/src/Components/Custom/AddressInput.tsx, packages/WebApp/src/Components/Custom/CustomDrawer.tsx, packages/WebApp/src/Components/Pages/MainPage.tsx
Adds a formik wrapped address input which allows for toggling between using the sender address or the typed address
=> Address input added

src/App.tsx, src/Components/Custom/TokenInput.tsx, src/Components/Custom/TokenSelectInput.tsx, src/Components/Pages/MainPage.tsx, src/Contexts/ChainbridgeContext.tsx, src/Contexts/Reducers/TransitMessageReducer.tsx, src/Modules/PreflightModal.tsx, src/Modules/TransactionActiveModal.tsx, src/chainbridgeConfig.ts
Wire up TX Error handling
Voter records
Final Transfer TX Hash
Minor other UX fixes
=> UX Improvements

package.json, src/App.tsx, src/Components/Pages/WrapperPage.tsx, src/Contexts/ChainbridgeContext.tsx, src/Modules/TransferActiveModal.tsx, src/Modules/WrapActiveModal.tsx, src/chainbridgeConfig.ts, yarn.lock
- Allows to configure gas price for a network
- Fixes fee not added to Deposit TX causing revert
- Adds progress bar to TX modals
=> Release 2020-12-02

package.json, src/Contexts/ChainbridgeContext.tsx, yarn.lock
This PR includes the following changes:
- Handle varying token decimals in Bridge.deposit()
- Handle USDT ERC20 approval issues
- Handle websocket RPC
=> Various Fixes and Optimizations

src/Modules/TransferActiveModal.tsx
=> Display Executing Proposal state

package.json, src/App.tsx, yarn.lock
Update common-theme package to 1.0.10
=> Update theme package and NeueMontreal font

src/Components/Pages/TransferPage.tsx, src/Contexts/Adaptors/SubstrateAdaptors.tsx, src/Contexts/Adaptors/interfaces.tsx
Allow users to choose the active account when home chain is substrate
=> Substrate account selector

.gitignore, .vscode/settings.json, src/Components/Pages/TransferPage.tsx
=> inverted Token and amount fields order 

src/Layouts/AppHeader.tsx, src/Layouts/AppWrapper.tsx
=> Fix mobile rendering

src/Contexts/Adaptors/EVMAdaptors.tsx
=> Celo adaptor

src/Contexts/Adaptors/EVMAdaptors/helpers.ts
added connect to RPC with username and password if provided 
Closes: #111 
- add rpcUrl like "https://john:doe@host"
- try to transfer the token to this chain
=> https basic auth

config/chainbridge-runtime-config.evm.js, jest.config.js, package.json, src/Components/Custom/DetailView.test.tsx, src/Components/Custom/DetailView.tsx, src/Components/Custom/ExplorerTable.tsx, src/Components/Custom/__snapshots__/DetailView.test.tsx.snap, src/Components/Pages/ExplorerPage.test.tsx, src/Components/Pages/ExplorerPage.tsx, src/Components/Pages/__snapshots__/ExplorerPage.test.tsx.snap, src/Contexts/ExplorerContext.tsx, src/Contexts/Reducers/TransfersReducer.tsx, src/Layouts/AppHeader.tsx, src/Layouts/AppWrapper.tsx, src/Services/ExplorerService.tsx, src/Utils/Helper.test.ts, src/Utils/Helpers.tsx, src/Utils/TestUtils.ts, src/setupTests.ts, src/types/globals.ts, src/types/mutationobserver.shim.d.ts
Implement transfer from API for the Explorer view. Added some unit test and some refactors in order for the view to work with the API.
Closes: #<issue>
=> Fetch data from API for Explorer view

README.md, src/Components/Pages/TransferPage.tsx, src/Contexts/Adaptors/EVMAdaptors/EVMHomeAdaptorProvider.tsx, src/Contexts/Adaptors/EVMAdaptors/helpers.ts, src/Contexts/Adaptors/SubstrateAdaptors.tsx, src/chainbridgeConfig.ts
=> Decimal option for tokens

README.md, config/chainbridge-runtime-config.celo.js, config/chainbridge-runtime-config.evm.js, src/Components/Pages/TransferPage.tsx, src/Contexts/Adaptors/EVMAdaptors/EVMDestinationAdaptorProvider.tsx, src/Contexts/Adaptors/EVMAdaptors/EVMHomeAdaptorProvider.tsx, src/Contexts/Adaptors/SubstrateAdaptors.tsx, src/Contexts/Adaptors/SubstrateApis/ChainBridgeAPI.tsx, src/Contexts/Adaptors/interfaces.tsx, src/Contexts/ChainbridgeContext.tsx, src/Contexts/ExplorerContext.tsx, src/Contexts/NetworkManagerContext.tsx, src/Contexts/Reducers/TransfersReducer.tsx, src/chainbridgeConfig.ts
Changes and rename chainId for domainId. Closes #115 
Closes: #<issue>
Manual test were executed
=> Renaming chainId for domainId

src/Contexts/Adaptors/EVMAdaptors/EVMDestinationAdaptorProvider.tsx, src/Contexts/Adaptors/SubstrateAdaptors.tsx, src/Contexts/ChainbridgeContext.tsx, src/Contexts/NetworkManagerContext.tsx, src/Contexts/Reducers/TransitMessageReducer.tsx, src/Modules/TransferActiveModal.tsx
=> Fix race conditions for messages displayed on TransferActiveModal

src/App.tsx, src/Components/Routes.tsx, src/Layouts/AppWrapper.tsx, src/Modules/TransferActiveModal.tsx, src/chainbridgeConfig.ts, src/types/globals.ts
Enable conditional render for Token Wrap page using runtime config
Closes: #131
=> Conditional render for wrap page

src/Components/Pages/TransferPage.tsx, src/Components/Pages/WrapperPage.tsx
Fix for predefined icon behavior on the wrap token page
Closes: #109
=> Fix icons behavior on wrap token page

config/chainbridge-runtime-config.celo.js, src/Components/Custom/DetailView.tsx, src/Components/Custom/__snapshots__/DetailView.test.tsx.snap, src/Utils/Helpers.tsx
=> Minor explorer fixes

src/Components/Custom/DetailView.tsx, src/Components/Custom/ExplorerTable/ExplorerTable.tsx, src/Components/Custom/__snapshots__/DetailView.test.tsx.snap, src/Components/Pages/__snapshots__/ExplorerPage.test.tsx.snap
=> Use chain name from config

README.md, src/Contexts/Adaptors/EVMAdaptors/EVMHomeAdaptorProvider.tsx, src/chainbridgeConfig.ts
I've created a flag for double approval logic in some cases like USDT or cUSD
Closes: #152
=> Double approval flag

src/Contexts/Adaptors/EVMAdaptors/EVMHomeAdaptorProvider.tsx, src/types/globals.ts
As metamask's docs recommend we will reload the page on chain changed 
Closes: #151
=> UI used wrong bridge address

package.json, src/App.tsx, src/contexts/Adaptors/EVMAdaptors/EVMHomeAdaptorProvider.tsx, src/contexts/ChainbridgeContext/ChainbridgeContext.tsx, src/contexts/NetworkManagerContext/NetworkManagerContext.tsx, src/contexts/index.ts, src/contexts/localWeb3Context/index.ts, src/contexts/localWeb3Context/localWeb3Context.tsx, src/contexts/localWeb3Context/localWeb3Reducer.ts, src/contexts/localWeb3Context/types.ts, src/pages/TransferPage/TransferPage.tsx, src/utils/LocalNetworksHelpers.ts, src/utils/localNetworksHelpers.ts
Fix to manage the UI to work with local and testnet networks. Refactored web3 context logic
Closes: #145 
Manual test between local networks with new contracts and testnets had been done
=> Fixing UI to work with local networks and some refactor

src/contexts/localWeb3Context/localWeb3Context.tsx, src/contexts/localWeb3Context/localWeb3Reducer.ts, src/utils/localNetworksHelpers.ts
=> Removing logs from main

lerna.json, package.json, packages/basic-example/package.json, packages/core/src/contexts/ExplorerContext/ExplorerContext.tsx, packages/core/src/reducers/TransfersReducer.tsx, packages/core/src/services/ExplorerService/ExplorerService.tsx, packages/example/package.json, packages/example/src/components/ExplorerTable/ExplorerTable.tsx, packages/example/src/pages/ExplorerPage/ExplorerPage.tsx, packages/example/src/pages/ExplorerPage/MyAllSwitch.tsx, packages/example/src/pages/ExplorerPage/SelectNetwork.tsx, packages/example/src/pages/ExplorerPage/styles.ts, yarn.lock
=> Filters for explorer 

packages/core/src/contexts/NetworkManagerContext/NetworkManagerContext.tsx, packages/core/src/contexts/localWeb3Context/customHook/useOnboard.tsx, packages/core/src/contexts/localWeb3Context/localWeb3Context.tsx, packages/core/src/contexts/localWeb3Context/types.ts, packages/core/src/utils/localNetworksHelpers.ts, packages/transfer-widget-example/README.md, packages/transfer-widget-example/src/App.css, packages/transfer-widget-example/src/App.tsx, packages/transfer-widget/README.md, packages/transfer-widget/src/App.tsx, packages/transfer-widget/src/modules/NetworkUnsupportedModal/NetworkUnsupportedModal.tsx, packages/transfer-widget/src/pages/TransferPage/HomeNetworkConnectView.tsx, packages/transfer-widget/src/pages/TransferPage/TransferPage.tsx
=> external wallet connection for widget

packages/core/src/contexts/localWeb3Context/localWeb3Context.tsx
Closes: #242 
Create only two networks in the `public/chainbridge-runtime-config.js`
=> fix event type name to "setDestinationChain"

packages/explorer-ui/Dockerfile
Dockerfile for `explorer-ui` deploy
Closes: #252
=> dockerfile for explorer ui

README.md
Removed ChainSafe in various places within the project README for legal reasons
Closes: #<issue>
=> company association fixes

README.md, docker-compose.yml, packages/config-server/README.md, packages/example/README.md
=> Deployment readme for TransferUI and Config server

.github/workflows/deploy_ecs-config-server_STAGE.yaml, .github/workflows/deploy_ecs-explorer-ui_STAGE.yaml, .github/workflows/deploy_ecs-transfer-ui_STAGE.yaml, Dockerfile, docker-compose.yml, ecs/task_definition-config-server-STAGE.json, ecs/task_definition-explorer-ui-STAGE.json, ecs/task_definition-transfer-ui-STAGE.json, etc/nginx.conf, packages/config-server/package.json, packages/config-server/src/index.ts, server.dockerfile, yarn.lock
=> ECS Services: Explorer, Transfer and ConfigServer
